// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <Arduino_ESP32_OTA.h>

const char DEVICE_LOGIN_NAME[] = "0c8e178e-ca3d-4f11-9685-8161231aabe6";

const char SSID[] = "****";           // Network SSID (name)
const char PASS[] = "****";                   // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = "****"; // Secret device password

void onHUMChange();
void onPRESSChange();
void onTEMPChange();

float HUM;
float PRESS;
float TEMP;

void initProperties()
{

    ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
    ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
    ArduinoCloud.addProperty(HUM, READWRITE, ON_CHANGE, onHUMChange);
    ArduinoCloud.addProperty(PRESS, READWRITE, ON_CHANGE, onPRESSChange);
    ArduinoCloud.addProperty(TEMP, READWRITE, ON_CHANGE, onTEMPChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
