// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <Arduino_ESP32_OTA.h>

const char DEVICE_LOGIN_NAME[] = "c35b9c1e-3b21-4644-bf06-6214b94a5278";

const char SSID[] = "****";           // Network SSID (name)
const char PASS[] = "****";                   // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = "****"; // Secret device password

void onLEDTEST2Change();

float LED_TEST2;

void initProperties()
{

    ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
    ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
    ArduinoCloud.addProperty(LED_TEST2, READWRITE, ON_CHANGE, onLEDTEST2Change);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
